<?php include('head.php'); ?>
<?php include('menu-page-dark.php'); ?>

	<div id="page" class="page">
        
        <div class="header-page padd-y-75 marg-top-100 bg-fs-clr">
        
            <div class="title-page padd-x-25 wh-clr">FAQs</div>
            
        </div>
                            
        <div class="post-wrap padd-y-50 boxed">
                            
            <article class="row">
            
                <div class="post-content padd-x-25">
                    
                    <div class="col-1-2 padd-right-50 padd-bott-25"> 
                            
                        <h3>Frequently Asked Questions</h3>
                        
                        <div id="ui-accordion">
                            <strong class="brd-fs-clr">What's the token of this System?</strong>
                            <div class="brd-fs-clr">
                                PLAY shares (PLS) are the tokens of the system. PLS are designed first to be the shares of the BitShares Play System, and thus the unit in which dividends are paid to PLS holders and delegates of PLAY are paid for their contributions to the system. Secondly, PLS are the token with which users purchase game assets to play games. PLS provides an opportunity to expand the model of token distribution, and may explore models in which a game rewards winners with the tokens of the game system itself.
                            </div>
                            
                            <strong class="brd-fs-clr">The difference between game coins in BitShares Play and BitAssets in BTSX?</strong>
                            <div class="brd-fs-clr">
                                CHIPS are different from BitShares X market issued assets like BitUSD and user issued assets. There is an exchange model between PLS and chips, and no market, which is part the BitShares Play consensus, Every chip asset is created with some PLS collateral recorded by the system, and a total supply. After creation, the PLS amount will be frozen as collateral in the system’s balance.
                            </div>
                            
                            <strong class="brd-fs-clr">What's the consensus algorithm used in BitShares Play?</strong>
                            <div class="brd-fs-clr">
                                BitShares Play is using DPOS. The advantage of DPOS is that it allows for faster block confirmation and also allows for scalability to the level of VISA's 10,000 payment transactions per second. Meanwhile the system is still decentralized in that there is neither a single point of failure nor a single point of control. Delegates have the rather simple job of signing new blocks and can be fired on command if they do not perform their duties. Consensus on a whole is reached by stakeholders, whereas in traditional Proof Of Work schemes only hashing participants contribute to the network consensus, leaving shareholders who don’t mine unrepresented.
                            </div>
                            
                            <strong class="brd-fs-clr">What's the Random Number Generation(RNG) algorithm in BitShares Play?</strong>
                            <div class="brd-fs-clr">
                                BitShares Play is using a provable distributed RNG algorithm from DPOS. “Distributed” means that the random number of one block is generated by the previous 101 delegates’ revealed secret, so as long as at least one of them are honest, the resulting random number is truly random. “Provable” means that they need to publish the hash of their secrets to the blockchain in the next round. The revealed secret’s hash must be the hash they published last time. They can not cheat by revealing selective favourable secret because the hash of the secret must be included in previous produced block.
                            </div>
                            
                            <strong class="brd-fs-clr">What's the meaning of decentralized market place and platform?</strong>
                            <div class="brd-fs-clr">
                                There are two kinds of game coins in BitShares Play, one is the built-in on-chain games which need to meet the requirement of inner exchange model, the other one are coins sold by traditional game providers on BitShares Play. After the coins are sold, they can be deposit to the games for shopping, the left can be sold in the inner exhchange. For the second coins, the price for sell is decided and can be updated by the game providers.
                            </div>
                            
                            <strong class="brd-fs-clr">When will BitShares Play's snapshot occur?</strong>
                            <div class="brd-fs-clr">
                                The snapshot of BitShares Play will occur soon, please stay tuned!
                            </div>
                            
                            <strong class="brd-fs-clr">Is BitShares Play still focusing on gambling?</strong>
                            <div class="brd-fs-clr">
                                No, BitShares Play is no longer focus on gambling like Lotto, It is going to be built as a game assets platform.
                            </div>
                        </div> 
                        
                    </div>
                    	                    
                    <div class="clear"></div>
                        
                </div>
                
            </article>
                                                            
        </div>        
                
    </div>
    
<?php include('copy.php'); ?>
<?php include('foot.php'); ?>